### ISSUE TITLE
Provide arm64 image

### ISSUE THREAD

**Issue by matthewadams** [hivemq/hivemq4-docker-images#38]
I'm currently getting bitten by https://github.com/testcontainers/testcontainers-java/issues/5464: those with MBPs with Apple Silicon can't run integration tests with [hivemq/hivemq-ce:2021.3](https://hub.docker.com/layers/hivemq-ce/hivemq/hivemq-ce/2021.3/images/sha256-9f18f8e1b124f3abeca5ab3645b83ce1e23fff8fedad194e3d6e73794c2c4ca1?context=explore).

Please provide a `hivemq/hivemq-ce` Docker image for the `arm64` architecture.

**Comment by SgtSilvio** [comment]
Multi-arch images for hivemq-ce are provided since release [2024.3](https://github.com/hivemq/hivemq-community-edition/releases/tag/2024.3)
