### ISSUE TITLE
BUG - config.xml in master is invalid 

### ISSUE THREAD

**Issue by stefanjay** [hivemq/hivemq4-docker-images#45]
Hey there,

please fix the config.xml due to the new xml linter introduced in 4.10.0.

In line `32` of file config.xml in `<root>/hivemq4/k8s-image/config.xml`:

Error of the hivemq log running in k8s:

```
hivemq 2022-12-29 14:32:18,249 INFO  - Log Configuration was overridden by /opt/hivemq/conf/logback.xml
hivemq 2022-12-29 14:32:18,859 WARN  - Cannot load the configuration from '/opt/hivemq/conf/config.xml' because of the following errors:
hivemq - XML schema violation in line '32' and column '11' caused by: "The element type "discovery" must be terminated by the matching end-tag "</discover ││ y>"."
hivemq 2022-12-29 14:32:18,860 ERROR - Preventing HiveMQ startup because the configuration could not be loaded.
```

Also please explain why the discovery extension var is gone.

Thanks, enjoy the ride to the new year :)

The best, Stefan.

**Comment by stefanjay** [comment]
Another found is, that because of the missing discovery entry, HiveMQ isn't able to jump into ClusterMode:

`│ 2022-12-30 12:54:19,341 WARN  - A Cluster discovery callback is present, but HiveMQ ist not configured to use extension discovery. Please check your configuration.                                               │`

**Comment by SgtSilvio** [comment]
Hi @stefanjay 

The config that is shipped with the image should work.
`<reload-interval>${HIVEMQ_DNS_DISCOVERY_INTERVAL}</reload-interval>` has always been wrong and was now removed because a wrong config is no longer allowed.

The config that we ship with and works is:
```
    <cluster>
        <enabled>true</enabled>
        <transport>
            <tcp>
                <bind-address>${HIVEMQ_BIND_ADDRESS}</bind-address>
                <bind-port>${HIVEMQ_CLUSTER_PORT}</bind-port>
            </tcp>
        </transport>
        <discovery>
            <extension/>
        </discovery>
    </cluster>
```

How do you run the image? Do you build an own image? Do you have a custom config? Maybe you ran into a different issue.

**Comment by stefanjay** [comment]
Hey @SgtSilvio,

thanks for your answer. Due to XML validation, using a XMLconfig with an closing tag but without a opening tag is invalid. You can also easily reproduce using the latest image `hivemq/hivemq4:k8s-4.11.0`. I used the original image from Dockerhub as described above and also the default `config.xml` got the log entries below.

```
│ hivemq 2023-01-10 20:28:45,394 INFO  - Starting HiveMQ Enterprise Server                                                                                                                                          │
│ hivemq 2023-01-10 20:28:45,396 INFO  - HiveMQ version: 4.11.0                                                                                                                                                     │
│ hivemq 2023-01-10 20:28:45,396 INFO  - HiveMQ home directory: /opt/hivemq                                                                                                                                         │
│ hivemq 2023-01-10 20:28:45,399 INFO  - Log Configuration was overridden by /opt/hivemq/conf/logback.xml                                                                                                           │
│ hivemq 2023-01-10 20:28:46,220 WARN  - Cannot load the configuration from '/opt/hivemq/conf/config.xml' because of the following errors:                                                                          │
│ hivemq     - XML schema violation in line '38' and column '11' caused by: "The element type "discovery" must be terminated by the matching end-tag "</discovery>"."                                               │
│ hivemq 2023-01-10 20:28:46,221 ERROR - Preventing HiveMQ startup because the configuration could not be loaded.                                                                                                   │
```

As the XML validation itself is "reading" trough the config and finds an error of a missing opening tag, the config with is shipped in the image is incorrect and also in this and other repos is. If you would like, I can also give you a brief demonstration in a short meeting.

I would also like to briefly note that I only want to report this one error and hope that this will not be taken as an insult. :)

**Comment by stefanjay** [comment]
Also how does the cluster DNS discovery now works? The nodes are now not able to "see" each other to bound into cluster mode. Please always remember we're talking about a default k8s setup.

**Comment by SgtSilvio** [comment]
Hi @stefanjay 

The default config in the k8s is correct, as you can see here: https://github.com/hivemq/hivemq4-docker-images/blob/master/hivemq4/k8s-image/config.xml#L31 

Did you use the hivemq helm-chart? Maybe the problem is caused by an outdated helm-chart. An `helm repo update` should fix this.

> I would also like to briefly note that I only want to report this one error and hope that this will not be taken as an insult. :)

No worries, same for us, we just want to find out the root cause of your issue.
