### ISSUE TITLE
Add support for license file via environment variable to normal base image

### ISSUE THREAD

**Issue by hertfelder** [hivemq/hivemq4-docker-images#7]
Please copy the following section into ```docker-entrypoint.sh``` of the normal base-image.

https://github.com/hivemq/hivemq4-docker-images/blob/8886b3042c1fd49156c5c9bcc3e41cf8cb3d9c0f/hivemq4/dns-image/docker-entrypoint.sh#L5-L9

**Comment by SgtSilvio** [comment]
Already done
