### ISSUE TITLE
Docker image of Community Edition (CE)

### ISSUE THREAD

**Issue by lutzhorn** [hivemq/hivemq4-docker-images#9]
Are there any plans to make a Docker image of the Community Edition (CE) available? The current image contains the Enterprise Edition.

Such an image would be useful to run HoveMQ as a [Testcontainer](https://www.testcontainers.org/).

**Comment by lutzhorn** [comment]
asked as https://github.com/hivemq/hivemq-docker-images/issues/5

**Comment by MagiErber** [comment]
Hi @lutzhorn,
nice to see your interest in our HiveMQ Community Edition. At the moment there are no plans to make a Docker image with our Community Edition, but we will welcome any contribution like this. Please feel free to create a Docker image with HiveMQ CE yourself and make a pull request to this repository.
Best regards,
Magi

**Comment by MicWalter** [comment]
An update: 

The docker image for the HiveMQ Community Edition will be part of the corresponding GitHub repository, see this [PR](https://github.com/hivemq/hivemq-community-edition/pull/99).

As was done with the two PR's #15 and #16, this issue will be closed.

Should there be any questions let me know.

Kind regards,
Michael from the HiveMQ team.
